### ISSUE TITLE
Doesn't work with flexbox - renders component 2x.

### ISSUE THREAD

**Issue by cellis** [misterfresh/react-easy-transition#14]
I'm trying to use this with flexbox. My html structure is as follows:

css
```css
.Site {
  display: flex;
  min-height: 100vh;
  flex-direction: column;
}

.Site-content {
  flex: 1;
}

#app {
  display: block;
}
```

html
```html
<body class="Site">
    <div class="Site-content">
        <div id="app">
             ... app rendered here ...
        </div>
    </div>
</body>
```

With the above css, a click on links does not transition correctly on the first click, and on the second click it renders a duplicate of the component.
